config/routes.rb
Rails.application.routes.draw do
  resources :ordersheets do
    collection {post :import}
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ordersheet.rb
class Ordersheet < ApplicationRecord
  def self.import(file)
  CSV.foreach(file.path, headers: true) do |row|
    Ordersheet.create! row.to_hash
  end
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/ordersheets_controller.rb
class OrdersheetsController < ApplicationController
  before_action :set_ordersheet, only: [:show, :edit, :update, :destroy]

  # GET /ordersheets
  # GET /ordersheets.json
  def index
    @ordersheets = Ordersheet.all
  end

  # GET /ordersheets/1
  # GET /ordersheets/1.json
  def show
  end

  # GET /ordersheets/new
  def new
    @ordersheet = Ordersheet.new
  end

  # GET /ordersheets/1/edit
  def edit
  end

  # POST /ordersheets
  # POST /ordersheets.json
  def create
    @ordersheet = Ordersheet.new(ordersheet_params)

    respond_to do |format|
      if @ordersheet.save
        format.html { redirect_to @ordersheet, notice: 'Ordersheet was successfully created.' }
        format.json { render :show, status: :created, location: @ordersheet }
      else
        format.html { render :new }
        format.json { render json: @ordersheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ordersheets/1
  # PATCH/PUT /ordersheets/1.json
  def update
    respond_to do |format|
      if @ordersheet.update(ordersheet_params)
        format.html { redirect_to @ordersheet, notice: 'Ordersheet was successfully updated.' }
        format.json { render :show, status: :ok, location: @ordersheet }
      else
        format.html { render :edit }
        format.json { render json: @ordersheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ordersheets/1
  # DELETE /ordersheets/1.json
  def destroy
    @ordersheet.destroy
    respond_to do |format|
      format.html { redirect_to ordersheets_url, notice: 'Ordersheet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
    Ordersheet.import(params[:file])
    redirect_to ordersheets_path, notice: "Upload Complete"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ordersheet
      @ordersheet = Ordersheet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ordersheet_params
      params.require(:ordersheet).permit(:uid, :license, :product_1, :product_2, :order_total, :pur_date, :f_name, :l_name, :address_1, :address_2, :city, :state, :zip, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ordersheets_helper.rb
module OrdersheetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ApiSales</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <script>
      $(document).ready(function(){
        $("#myInput").on("keyup", function() {
          var value = $(this).val().toLowerCase();
          $("#myTable tr").filter(function() {
            $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
          });
        });
      });
    </script>
  </body>
</html>

app/views/ordersheets/_form.html.erb
<%= form_with(model: ordersheet, local: true) do |form| %>
  <% if ordersheet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ordersheet.errors.count, "error") %> prohibited this ordersheet from being saved:</h2>

      <ul>
      <% ordersheet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :uid %>
    <%= form.number_field :uid, id: :ordersheet_uid %>
  </div>

  <div class="field">
    <%= form.label :license %>
    <%= form.text_field :license, id: :ordersheet_license %>
  </div>

  <div class="field">
    <%= form.label :product_1 %>
    <%= form.text_field :product_1, id: :ordersheet_product_1 %>
  </div>

  <div class="field">
    <%= form.label :product_2 %>
    <%= form.text_field :product_2, id: :ordersheet_product_2 %>
  </div>

  <div class="field">
    <%= form.label :order_total %>
    <%= form.number_field :order_total, id: :ordersheet_order_total %>
  </div>

  <div class="field">
    <%= form.label :pur_date %>
    <%= form.date_select :pur_date, id: :ordersheet_pur_date %>
  </div>

  <div class="field">
    <%= form.label :f_name %>
    <%= form.text_field :f_name, id: :ordersheet_f_name %>
  </div>

  <div class="field">
    <%= form.label :l_name %>
    <%= form.text_field :l_name, id: :ordersheet_l_name %>
  </div>

  <div class="field">
    <%= form.label :address_1 %>
    <%= form.text_field :address_1, id: :ordersheet_address_1 %>
  </div>

  <div class="field">
    <%= form.label :address_2 %>
    <%= form.text_field :address_2, id: :ordersheet_address_2 %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, id: :ordersheet_city %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state, id: :ordersheet_state %>
  </div>

  <div class="field">
    <%= form.label :zip %>
    <%= form.number_field :zip, id: :ordersheet_zip %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :ordersheet_email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ordersheets/edit.html.erb
<h1>Editing Ordersheet</h1>

<%= render 'form', ordersheet: @ordersheet %>

<%= link_to 'Show', @ordersheet %> |
<%= link_to 'Back', ordersheets_path %>

app/views/ordersheets/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="well">Ordersheets</h1>

<h3>Upload CSV File</h3>
  <%= form_tag import_ordersheets_path, multipart: true do %>
  <%= file_field_tag :file %>
</br>
  <%= submit_tag 'Upload', class: 'btn btn-primary' %>
<% end %>

</br>
<%= link_to 'Add To Ordersheet', new_ordersheet_path, class: 'btn btn-default' %>
</br>

<div class="row">
  <div class="col-md-3">
    <input class="form-control" id="myInput" type="text" placeholder="Search Datasheet">
  </div>
</div>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Uid</th>
      <th>License</th>
      <th>Product 1</th>
      <th>Product 2</th>
      <th>Order total</th>
      <th>Pur date</th>
      <th>F name</th>
      <th>L name</th>
      <th>Address 1</th>
      <th>Address 2</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id="myTable">
    <% @ordersheets.each do |ordersheet| %>
      <tr>
        <td><%= ordersheet.uid %></td>
        <td><%= ordersheet.license %></td>
        <td><%= ordersheet.product_1 %></td>
        <td><%= ordersheet.product_2 %></td>
        <td><%= ordersheet.order_total %></td>
        <td><%= ordersheet.pur_date %></td>
        <td><%= ordersheet.f_name %></td>
        <td><%= ordersheet.l_name %></td>
        <td><%= ordersheet.address_1 %></td>
        <td><%= ordersheet.address_2 %></td>
        <td><%= ordersheet.city %></td>
        <td><%= ordersheet.state %></td>
        <td><%= ordersheet.zip %></td>
        <td><%= ordersheet.email %></td>
        <td><%= link_to 'Show', ordersheet %></td>
        <td><%= link_to 'Edit', edit_ordersheet_path(ordersheet) %></td>
        <td><%= link_to 'Destroy', ordersheet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/ordersheets/new.html.erb
<h1>New Ordersheet</h1>

<%= render 'form', ordersheet: @ordersheet %>

<%= link_to 'Back', ordersheets_path %>

app/views/ordersheets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Uid:</strong>
  <%= @ordersheet.uid %>
</p>

<p>
  <strong>License:</strong>
  <%= @ordersheet.license %>
</p>

<p>
  <strong>Product 1:</strong>
  <%= @ordersheet.product_1 %>
</p>

<p>
  <strong>Product 2:</strong>
  <%= @ordersheet.product_2 %>
</p>

<p>
  <strong>Order total:</strong>
  <%= @ordersheet.order_total %>
</p>

<p>
  <strong>Pur date:</strong>
  <%= @ordersheet.pur_date %>
</p>

<p>
  <strong>F name:</strong>
  <%= @ordersheet.f_name %>
</p>

<p>
  <strong>L name:</strong>
  <%= @ordersheet.l_name %>
</p>

<p>
  <strong>Address 1:</strong>
  <%= @ordersheet.address_1 %>
</p>

<p>
  <strong>Address 2:</strong>
  <%= @ordersheet.address_2 %>
</p>

<p>
  <strong>City:</strong>
  <%= @ordersheet.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @ordersheet.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @ordersheet.zip %>
</p>

<p>
  <strong>Email:</strong>
  <%= @ordersheet.email %>
</p>

<%= link_to 'Edit', edit_ordersheet_path(@ordersheet) %> |
<%= link_to 'Back', ordersheets_path %>